source 'https://rubygems.org'

gem 'geocoder'
gem 'inifile'
gem 'nokogiri', '~> 1.11.4'
gem 'redcarpet'
gem 'simple-rss'
gem 'google_places'
gem 'icalendar'
gem 'linkeddata', '~> 2.0'
gem 'tess_api_client', git: 'git://github.com/ElixirTeSS/TeSS_api_client.git', tag: '0.3.3'
gem 'sanitize'
gem 'tess_rdf_extractors', :git => 'git://github.com/ElixirTeSS/TeSS_RDF_Extractors.git'
gem 'htmlentities'
