source 'https://rubygems.org'

gem 'geocoder', '~> 1.8.0'
gem 'inifile', '~> 3.0.0'
gem 'nokogiri', '~> 1.13.10'
gem 'redcarpet', '~> 3.5.1'
gem 'simple-rss', '~> 1.3.3'
gem 'google_places', '~> 2.0.0'
gem 'icalendar', '~> 2.8.0'
gem 'linkeddata', '~> 3.2.0'
gem 'tess_api_client', git: 'https://github.com/ElixirTeSS/TeSS_api_client', tag: '0.4.2'
gem 'sanitize', '~> 6.0.0'
gem 'tess_rdf_extractors', git: 'https://github.com/ElixirTeSS/TeSS_RDF_Extractors'
gem 'htmlentities', '~> 4.3.4'
gem 'sitemap-parser', '~> 0.5.6'
gem 'reverse_markdown', '~> 2.1.1'