source 'https://rubygems.org'

gem 'geocoder'
gem 'inifile'
gem 'nokogiri', '1.6.7.2'
gem 'redcarpet'
gem 'simple-rss'
gem 'tess_api_client', '0.0.7', :git => 'git://github.com/ElixirUK/TeSS_api_client.git'
#gem 'tess_api_client', '0.0.7', :path => '/Users/alex/work/ELIXIR/TeSS/code/TeSS_api_client'
#gem 'tess_api_client', '0.0.7', :path => '/Users/Beardface/Projects/TeSS_api_client'
