class TessApi
  require 'inifile'
  require 'net/http'
  require 'net/https'
  require 'material'
  require 'content_provider'
  require 'event'
  require 'json'
  require 'uploader'
  require 'config'
  require 'httparty'
  require 'rdfa_extractor'
  require 'json/ld'
  require 'nokogiri'
end
